### PR TITLE
🦊 Review

### PR DESCRIPTION
**Pull request by Retky**
## 1st Capstone Project

[Demo video](https://youtu.be/YG-mhD28pmo)

- Colors.
- Typography: font face, size and weight.
- Layout: composition and space between elements.

- Pages: 
  - The *home page*.
  - The *about page*.

- Display versions:
  - Mobile: up to 768px wide.
  - Desktop: 768px or wider.
- Interactions
  - Links
  - Mobile menu
  - The "Featured speakers" are created dynamically in JavaScript.

### CODE REVIEW

**Review by ReshyResh — CHANGES_REQUESTED** [review]
# Hi @Retky , 

### Good job so far with your capstone project, it looks amazing!
  - ✔ Great presentation video showcasing the website.
  - ✔ Design matches the Behance template.
  - ✔ Used correct semantic tags and made the website accessible.
  - ✔ No linter errors.


#### There are some issues that you still need to work on to go to the next module but you are almost there!


## Required Changes ♻️

- [x] Your website currently lacks a proper hero section, the main title (`<h1>`) is just a 'Welcome' text, with the actual text being an image, and not text that you could select. I suggest you try and give the website a proper welcome section by replacing the image (Which is also low resolution and might show up as pixellated on high resolution screens) with actual text, as in the Behance template.
- [x] You're currently missing the navigation bar that is above the main one, please make sure to add it to better match the template.

  
| Missing header  |
| ------------- |
|   |

- [x] The about page has a footer with a dark background color, yours is currently the same as the homepage, please make sure to change it to better match the given template.




Cheers and Happy coding! 👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Retky** [comment]
😃 Thank you @ReshyResh 
For the review, I'm working in the recommendations you mentioned.

**Review by elyor-doniyorov — APPROVED** [review]
Hi @Retky, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by Retky** [comment]
Thanks @elyor-doniyorov 
For the review.

**Pull request merged**
